### ISSUE TITLE
 Software Development : JSON RESTful API using PHP and MySQL (for CRUD)

### ISSUE THREAD

**Issue by imakshat47** [IEEESFIT1/OpenOctober#1]
A complete JSON RESTful API using PHP and MySQL. We will use the SlimPHP framework along with PDO to interact with the MySQL database.

RESTful API handles CRUD operations:
Reads Data from DB using GET Request
Create new entries using POST Request
Update record using PUT Request
Delete record using DELETE Request

**Comment by clare0901** [comment]
@imakshat47  Alright go ahead! Wish you luck!

**Comment by clare0901** [comment]
Kindly push your changes in the miscellaneous folder! Thanks!
