### ISSUE TITLE
Miscellaneous : Data structure and algorithm to implement Binary trees and its traversal

### ISSUE THREAD

**Issue by mayankmohak** [IEEESFIT1/OpenOctober#27]
Tree with in-order pre-order and post-order traversal

**Comment by csendranshi** [comment]
Please add your code in the [SoftwareDev](https://github.com/IEEESFIT1/OpenOctober/tree/master/SoftwareDev) folder for the respective language

**Comment by KartikeySharma** [comment]
Pls assign this to me if possible @csendranshi as it has been more than 2 days

**Comment by mayankmohak** [comment]
@KartikeySharma  sry i have made the pr.
maintainers sorry for delay i was busy in festival

**Comment by KartikeySharma** [comment]
@mayankmohak No problem
