### ISSUE TITLE
Miscellaneous: Python Inventory Management App 

### ISSUE THREAD

**Issue by imakshat47** [IEEESFIT1/OpenOctober#3]
### Python Inventory Management App  (WISPMS-Python)

> 
> ######  Warehouse Inventory Sales Purchase Management System (WISPMS) based on Python using Tkinter and Database
> 
> > 
> > ###### Python Project using Tkinter and Database
> > 
> > `Warehouse Inventory Sales Purchase Management System (WISPMS)`
> > 
> > > - Python 3.4.X
> > > - Sqlite DB / My SQL / Oracle
> > > - Tkinter

**Comment by orvil1026** [comment]
All the best!
