### ISSUE TITLE
Software Dev: C++ program on bellman-ford algorithm

### ISSUE THREAD

**Issue by RakshitaTantry28** [IEEESFIT1/OpenOctober#349]

**Comment by KartikeySharma** [comment]
@RakshitaTantry28 I have already contributed and implemented this algorithm. Pls have a look in the Graph Theory folder of Software Dev/C++

**Comment by Rakuzan98912** [comment]
@KartikeySharma O bhai itna stalk kaun karta hai dusron ke issues :)

**Comment by KartikeySharma** [comment]
I am just saying that see the repositories once before raising an issue. That's all. If I have already implemented it, then why implement it again (this is called redundancy) @Rakuzan98912

**Comment by csendranshi** [comment]
@RakshitaTantry28 This has already been implemented.
