### ISSUE TITLE
github action for greeting on PR is failing

### ISSUE THREAD

**Issue by mayankmohak** [IEEESFIT1/OpenOctober#86]
currently the github action for welcoming first issue or pr on repo is failing can i make subsequent changes.

**Comment by csendranshi** [comment]
It fails when the PR isn't the first contribution made by the user. The aim is to greet for the first time and it works fine for that. If you would like to make any additions to that, Please describe in detail.

**Comment by mayankmohak** [comment]
Actually As i can see the greet action if failing for all PRs (even first one).
Q.) Why is it so?
This is because github action doesn't work for pr's its a github bug.
Q.) What is the solution?
Make the respective changes is greet.yml file in workflows.

**Comment by mayankmohak** [comment]
@orvil1026  Have a look on this issue i can fix this issue.
