### ISSUE TITLE
There is a cpp file in  dir : OpenOctober/SoftwareDev/C/

### ISSUE THREAD

**Issue by mayankmohak** [IEEESFIT1/OpenOctober#87]
Provide its c alternative.

**Comment by mayankmohak** [comment]
@orvil1026 please can u assign me?

**Comment by csendranshi** [comment]
Which c++ file? Please describe the problem statement that you will be solving

**Comment by KartikeySharma** [comment]
@csendranshi The HELLO_WORLD file in the C folder was earlier saved in the format of HELLO_WORLD.cpp. 
This is what I believe @mayankmohak was trying to resolve.
However, the code inside the file was in C. So, I don't feel that there is an issue with that file as Cpp can run C codes using the extern "C" command.

**Comment by mayankmohak** [comment]
exactly @KartikeySharma  but it just to make things look clean and pretty.

**Comment by KartikeySharma** [comment]
I agree @mayankmohak. It was a minor issue and I think that the file has been deleted.

**Comment by KartikeySharma** [comment]
@orvil1026 @csendranshi I believe that this issue can be closed as no such file exists anymore.
